# Database and application deployment
# Add service below if test on production and run docker compose up -d
# See https://docs.docker.com/compose/compose-file/compose-file-v3/ for more detail
version: "3.7"
services:
  vending-machine-postgres:
    image: postgres:latest
    container_name: vending-machine
    environment:
      - POSTGRES_PASSWORD=qwertyasdfg
      - POSTGRES_DB=vending_machine
      - POSTGRES_USER=vending_machine_manager
    ports:
      - "5432:5432"
    volumes:
      - ./dbvolume:/var/lib/postgresql/data
