# Generated by Django 2.2.28 on 2023-01-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine_management', '0003_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendingMachine',
            new_name='Machine',
        ),
    ]
