# Generated by Django 2.2.28 on 2023-01-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine_management', '0004_auto_20230114_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='vending_machine',
            new_name='machine',
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('machine', 'product'), name='ux_product_list'),
        ),
    ]
