# Generated by Django 2.2.28 on 2023-01-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine_management', '0006_auto_20230114_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='created',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='last_modified',
        ),
    ]
