# Generated by Django 2.2.28 on 2023-01-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine_management', '0007_auto_20230114_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
