# Generated by Django 2.2.28 on 2023-01-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine_management', '0008_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
