# Generated by Django 2.2.28 on 2023-01-15 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine_management', '0010_auto_20230115_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
